name: Test staging runner

on:
  workflow_dispatch:

jobs:
  test-runner:
    runs-on: [self-hosted, linux, x64, staging]

    steps:
      - name: Show basic info
        run: |
          whoami
          hostname
          pwd
          uname -a

      - name: Check Docker
        run: |
          docker --version
<<<<<<< HEAD
          docker compose version
=======
          docker compose version
>>>>>>> 84e63a8b02521e06ccf37f797ece518f0be5c18c
